// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (medication_id, quantity, expiry_date, location)
VALUES ($1, $2, $3, $4)
RETURNING id, medication_id, quantity, expiry_date, location, created_at
`

type CreateInventoryItemParams struct {
	MedicationID int64       `json:"medication_id"`
	Quantity     int32       `json:"quantity"`
	ExpiryDate   pgtype.Date `json:"expiry_date"`
	Location     *string     `json:"location"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.MedicationID,
		arg.Quantity,
		arg.ExpiryDate,
		arg.Location,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.MedicationID,
		&i.Quantity,
		&i.ExpiryDate,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT
    ii.id,
    ii.medication_id,
    m.name   AS medication_name,
    ii.quantity,
    ii.expiry_date,
    ii.location,
    ii.created_at
FROM inventory_items ii
JOIN medications m ON m.id = ii.medication_id
ORDER BY ii.created_at DESC
`

type ListInventoryItemsRow struct {
	ID             int64              `json:"id"`
	MedicationID   int64              `json:"medication_id"`
	MedicationName string             `json:"medication_name"`
	Quantity       int32              `json:"quantity"`
	ExpiryDate     pgtype.Date        `json:"expiry_date"`
	Location       *string            `json:"location"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInventoryItems(ctx context.Context) ([]ListInventoryItemsRow, error) {
	rows, err := q.db.Query(ctx, listInventoryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryItemsRow
	for rows.Next() {
		var i ListInventoryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationID,
			&i.MedicationName,
			&i.Quantity,
			&i.ExpiryDate,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
