// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medications.sql

package db

import (
	"context"
)

const createMedication = `-- name: CreateMedication :one
INSERT INTO medications (name, barcode, active_ingredient)
VALUES ($1, $2, $3)
RETURNING id, name, barcode, active_ingredient
`

type CreateMedicationParams struct {
	Name             string  `json:"name"`
	Barcode          *string `json:"barcode"`
	ActiveIngredient *string `json:"active_ingredient"`
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, createMedication, arg.Name, arg.Barcode, arg.ActiveIngredient)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.ActiveIngredient,
	)
	return i, err
}
