// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryItem struct {
	ID           int64              `json:"id"`
	MedicationID int64              `json:"medication_id"`
	Quantity     int32              `json:"quantity"`
	ExpiryDate   pgtype.Date        `json:"expiry_date"`
	Location     *string            `json:"location"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Medication struct {
	ID               int64   `json:"id"`
	Name             string  `json:"name"`
	Barcode          *string `json:"barcode"`
	ActiveIngredient *string `json:"active_ingredient"`
}
